language: R
sudo: false
cache: packages
env:
  global:
    secure: KFqYE9O8jm5nxxaqTMPV9Gf5ExcKxL2doj5XMVeDHmz25F02EF66jdeCTmHioqshr9WMv2L1XM8weIPEWHmutpObmG72v88LxVj0XTvWdb8jyySwE/hDiypIdZn2Sz/YjPl5JWCKkuY8jNR3P+z85TzfvSHvbGK3lnZRd59+0vXfh/IShtmOWO9jRP8XTGR5mnqvDqOM6Qs/6OcHLuaLhaL2CKMvLkUQSkzBPJ8gW4ehOM9WG+jnzkQyDqJq9L9gCrVMHlGq5e24rZQpKH66Y3K5LP0lG4XV6KZanmqrG50HJKNmvpLIwXNL0W3VLVy8kFHlADNEWY1w5CrWMCuqV2zT+GQQEe2CognWysfbYdECjp/Khl2pdxgDdAoRZWUdJoEMsIhv71ISf/GfjXqA03WBJHCbuC1qQ/YLfJ+lQpeFFppk2BwNTQs9juXG/IOOS8Cx1T7DaFQ9MX3JcLXtQaJjSOMB1PZi4/gIRORDgS457dmHXOzVWvbkuUgXlIp5iIHVdTWMux1nWBEAlatlrq/3qZe40vSGwR1lg0gBdSfcvd6sUtOFPYw3Ym7qNnzORRPEzaymmTqsID+Q8RYZtT4NlnVCLLikCVZdsVe1eQn5F062e+JNkhZAnC3ksjltUegnVAK6u7a050lp9GuD7pae3eJcmbaiissLORHgRWs=
