---
title: "Abstract"
author: "R Clay Wright"
date: "12/9/2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract for Homebrew Con 2018

### Subject:  
Recipe Formulation & Improvement – seminars designed to help the audience 
improve their homebrew or design the best beer possible.  


### Title:  
StyleSpace: the final beer frontier. To explore strange new styles, to seek out 
new flavors and new combinations, to boldly go where no beer has gone before.  

### Brief description (75 words, published):


### Detailed description (unlimited, for selection committee)


### Other questions:

Will we serve beer?

Your profile:
Spoken at Homebrew Con before? * Please select one
Public Speaking Experience * Please select one
If you would like the AHA to publish a link to your Facebook page, or your company/club's Facebook page in your seminar listing on the Homebrew Con website & app, please provide a link to it here 
If you would like the AHA to publish your Twitter handle, or your company/club's Twitter handle in your seminar's listing on the Homebrew Con website & app, please provide it here 
If you would like the AHA to publish your Instagram handle, or your company/club's Instagram handle in your seminar's listing on the Homebrew Con website & app, please provide it here 
If selected, would you like to have your e-mail address included in your biography in the program and on the website for attendees to contact you if they have further questions about your talk after the conference? Please select one
Mailing Address *  
City * 
State/Province * 
Zip *  
Biography * Characters left: 600  
Profile Photo * 


